library identifier: "pipeline-library@v1.6",
retriever: modernSCM(
  [
    $class: "GitSCMSource",
    remote: "https://github.com/redhat-cop/pipeline-library.git"
  ]
)

pipeline {
    agent {
        label 'maven'
    }

    stages {
        stage('Git Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Maven Build') {
            steps {
                dir('sim-traffic-light') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Container Build') {
            steps {
                binaryBuild(projectName: 'cicd', buildConfigName: 'sim-traffic-light', buildFromPath: 'sim-traffic-light')
            }
        }
    }
}