node('maven') {
    stage('Build') {
        checkout scm
        dir('sim-rag-score'){
            sh 'mvn clean package'
            archiveArtifacts artifacts: 'target/sim-rag-score.jar', fingerprint: true
        }
    }
    stage('Test') {
        echo 'Testing....'
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
}