node {
    stage('Build') {
        checkout scm
        sh 'cd sim-rag-score'
        sh './mvnw clean package'
        archiveArtifacts artifacts: 'target/sim-rag-score.jar', fingerprint: true
    }
    stage('Test') {
        echo 'Testing....'
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
}