apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sim-traffic-light
  namespace: cicd
spec:
  source:
    type: binary
    binary: {}
  strategy:
    type: Docker
  triggers: []
  output:
    to:
      kind: ImageStreamTag
      name: "sim-traffic-light:latest"
    imageLabels:
      - name: "name"
        value: "sim-traffic-light"
      - name: "summary"
        value: "Decision Service for Straw Incorporation Measure Traffic Light"
    